language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - nosetests
  - python setup.py cram
before_install:
- sudo apt-get install -y libhdf5-serial-dev
